# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Nightly

on:
  schedule:
    - cron:  '15 19 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.5
      with:
        ref: main
    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 17
        distribution: "temurin"
    - name: Build with Maven
      run: mvn -B clean package
    - name: Cache Maven packages
      uses: actions/cache@v4.0.2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2



